--require("bufferline").setup {
--    options = {
--        mode = "tabs",
--        numbers = "ordinal",
--        diagnostics = "nvim_lsp",
--        color_icons = true,
--        separator_style = "padded_slant",
--        offsets = {
--            {
--                filetype = "NvimTree",
--                text = "File Explorer",
--                text_align = "center",
--                separator = true
--            }
--        }
--    },
--}
