windowrule {
    name = "No Hyprbars on tiled windows"
    match:float = false

    hyprbars:no_bar = true
}

$wscolor= rgb(a6da95)

plugin {
    hyprbars {
        enabled = true
        bar_height = 28
        bar_color = rgb(1e1e1e)
        col.text = rgb(ffffff)
        bar_text_size = 12
        bar_text_font = Symbols Nerd Font
        bar_button_padding = 12
        bar_padding = 10
        bar_precedence_over_border = true

        hyprbars-button = rgb(ed8796), 18, , hyprctl dispatch killactive
        hyprbars-button = rgb(eed49f), 18, , hyprctl dispatch fullscreen 2
        hyprbars-button = rgb(8aadf4), 18, , hyprctl dispatch togglefloating
   }
}
