theme {
    style = Breeze
    color_scheme = /usr/share/color-schemes/BreezeDark.colors
    # icon_theme = Cosmic
    # font_size = 30
    # font = "JetBrains Mono"
}

misc {
    single_click_activate = true
    menus_have_icons = true
    shortcuts_for_context_menus = true
}
