max-gamma = 150

$start = 17

profile {
    time = 7:30
    identity = true
}

profile {
    time = $start:00
    temperature = 6000
}

profile {
    time = $start:30
    temperature = 4500
}

profile {
    time = {{ start + 1 }}:00
    temperature = 3000
}
