#!/usr/bin/env sh

printenv

# hyprctl dispatch focuswindow "discord"
# sleep 0.25
# ydotool type "$(rmpc song --path "$CURRENT_SONG" | jq -r '"Now playing: \(.metadata.artist) - \(.metadata.title)"')" -d 2
# ydotool key 28:1 28:0
