return {}
-- return {
-- 	{
-- 		"folke/edgy.nvim",
-- 		event = "VeryLazy",
-- 		init = function()
-- 			local edgy = require("edgy")
--
-- 			vim.opt.laststatus = 3
-- 			vim.opt.splitkeep = "screen"
--
-- 			vim.keymap.set("n", "<leader>st", function()
-- 				edgy.toggle("left")
-- 			end, { desc = "Toggle sidebar" })
-- 		end,
-- 		dependencies = {
-- 			{
-- 				"folke/trouble.nvim",
-- 				dependencies = "nvim-tree/nvim-web-devicons",
-- 				keys = {
-- 					{
-- 						"<leader>tt",
-- 						"<cmd>Trouble symbols toggle<cr>",
-- 						desc = "Symbols (Trouble)",
-- 					},
-- 					{
-- 						"<leader>tm",
-- 						"<cmd>Trouble diagnostics toggle<cr>",
-- 						desc = "Diagnostics (Trouble)",
-- 					},
-- 				},
-- 				opts = {
-- 					restore = false,
-- 					auto_close = false,
-- 					-- auto_preview = true,
-- 					open_no_results = true,
-- 					pinned = true,
-- 					multiline = false,
-- 					auto_preview = false,
-- 					preview = {
-- 						type = "main",
-- 						scratch = false,
-- 					},
-- 				}, -- for default options, refer to the configuration section for custom setup.
-- 				-- init = function()
-- 				-- 	-- vim.api.nvim_create_autocmd("BufReadPost", {
-- 				-- 	-- 	pattern = "*",
-- 				-- 	-- 	callback = function()
-- 				-- 	-- 		require("trouble").refresh()
-- 				-- 	-- 	end,
-- 				-- 	-- })
-- 				-- end,
-- 			},
-- 		},
-- 		opts = {
-- 			options = {
-- 				left = {
-- 					size = 35,
-- 				},
-- 			},
-- 			exit_when_last = true,
-- 			close_when_all_hidden = true,
-- 			left = {
-- 				{
-- 					ft = "trouble",
-- 					pinned = true,
-- 					title = "Symbols",
-- 					-- filter = function(_buf, win)
-- 					-- print(vim.inspect(vim.w[win]))
-- 					-- return vim.w[win].trouble.mode == "symbols"
-- 					-- end,
-- 					open = "Trouble symbols position=left focus=false",
-- 					size = { height = 0.6 },
-- 				},
-- 				{
-- 					ft = "trouble",
-- 					pinned = true,
-- 					title = "Diagnostics",
-- 					-- filter = function(_buf, win)
-- 					-- 	-- return vim.w[win].trouble.mode == "diagnostics"
-- 					-- end,
-- 					open = "Trouble diagnostics focus=false filter.severity=vim.diagnostic.severity.ERROR",
-- 					size = { height = 0.4 },
-- 				},
-- 			},
-- 		},
-- 	},
-- }
